services:
  - type: web
    name: linkedin-guru-server
    env: node
    plan: free
    region: ohio
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false" # Permitir descarga en Render si no hay Chrome global
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
